# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pa11y accessibility test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g pa11y-ci

    - name: Run pa11y accessibility test
      run: npm run pa11y-cipa11y-ci --sitemap https://pa11y.org/sitemap.xml > tee pa11y-report

    - name: Upload pa11y report
      uses: actions/upload-artifact@v2.2.4
      with:
        name: pa11y-report
        path: report.json
