# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pa11y accessibility test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g pa11y-ci

      - name: Run pa11y accessibility test
        run: pa11y-ci --sitemap https://pa11y.org/sitemap.xml 2>&1 | tee pa11y-report.json

      - name: Upload pa11y report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pa11y-report
          path: pa11y-report.json
